### ISSUE TITLE
Compile error on windows

### ISSUE THREAD

**Issue by xmxiaoq** [go-cmd/cmd#12] opened 2018-04-24 08:01 UTC
.\cmd.go:192:9: undefined: syscall.Kill
.\cmd.go:244:48: unknown field 'Setpgid' in struct literal of type syscall.SysProcAttr

**Comment by daniel-nichter** [comment] 2018-04-28 22:41
Sorry, this pkg doesn't work on Windows and there are no plans to support Windows. (Duplicate of issues #2 and #5)

**Closed by daniel-nichter** 2018-04-28 22:41 UTC

**Comment by daniel-nichter** [comment] 2019-11-24 21:56
Windows should work as of v1.1.0.
